---
- name: Ensure nginx is installed.
  ansible.builtin.package:
    name: nginx
    state: present
  become: true
- name: Ensure nginx is enabled.
  ansible.builtin.systemd:
    name: nginx
    enabled: true
  become: true
