version: "3.3"

services:
  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /home/adevries/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - CLOUDFLARE_EMAIL=admin@turtlesnet.cloud
      - CLOUDFLARE_API_KEY=
    command:
      - "--log.level=debug"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.delayBeforeCheck=0"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.0.0.1:53"
      - "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.cloudflare.acme.email=admin@turtlesnet.cloud"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
  nginx:
    image: nginx
    container_name: nginx-traefik
    labels:
      - traefik.http.routers.nginx.rule=Host(`nginx.turtlesnet.cloud`)
      - traefik.http.routers.nginx.tls.certresolver=cloudflare


  # mysql:
  #   image: mariadb
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=
  #     - MYSQL_PASSWORD=
  #     - MYSQL_DATABASE=nextcloud
  #     - MYSQL_USER=nextcloud
  #   volumes:
  #     - /mnt/db/mysql:/var/lib/mysql


  # nextcloud:
  #   image: nextcloud:27
  #   depends_on:
  #     - mysql
  #   labels:
  #     - "traefik.http.routers.nextcloud.rule=Host(`nc.turtlesnet.cloud`)"
  #   volumes:
  #     - /mnt/nextcloud

  # jellyfin:
  #   image: jellyfin/jellyfin
  #   container_name: jellyfin
  #   network_mode: 'host'
  #   volumes:
  #     - /mnt/jellyfin/config:/config
  #     - /mnt/jellyfin/cache:/cache
  #     - /mnt/jellyfin/media:/media
  #     - /mnt/jellyfin/music:/music
  #   restart: 'unless-stopped'
  #   # Optional - alternative address used for autodiscovery
  #   environment:
  #     - JELLYFIN_PublishedServerUrl=http://jellyfin.turtlesnet.cloud
  #   # Optional - may be necessary for docker healthcheck to pass if running in host network mode
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ports:
  #     - 8096:8096
  #     - 8920:8920