---
all:
  children:
    proxmox:
      hosts:
        saturn2:
          ansible_ssh_user: root
        jezreel:
          ansible_ssh_user: root
        david:
          ansible_ssh_user: root
        pbs:
          ansible_ssh_user: root
    docker:
      hosts:
        jellyfin:
        gunnerarma3:
        nextcloud:
    ungrouped:
      hosts:
        avorion:
