---
- name: Configure ansible controllers.
  hosts: localhost
  roles:
    - common
    - geerlingguy.docker
  vars_files:
    - vars/vault.yml
  tags: controllers
  become: true
  tasks:
    - name: Install common tools
      ansible.builtin.dnf:
        name:
          - just
          # rust dependencies
          - dnf-plugins-core
          - cmake
          - gcc
          - clang
          - make
          # ansible stuff
          - python3-pip
          - ansible-lint
        state: present
      become: true

    - name: Configure git username
      community.general.git_config:
        name: user.name
        scope: global
        value: "Andrew DeVries"
      become: false

    - name: Configure git email
      community.general.git_config:
        name: user.email
        scope: global
        value: "andrew@andrewdevries.net"
      become: false

    - name: Configure hosts file.
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          # billadeau things
          100.110.172.147 gitlabs.zabilladeau.com gitlabs
        marker: "# {mark} ANSIBLE MANAGED"
        state: present
      become: true

    - name: Install pip tools.
      ansible.builtin.pip:
        name:
          - linode-cli
        state: present
      become: false

    - name: Create ssh config.
      ansible.builtin.file:
        path: ~/.ssh/config
        state: touch
        mode: "0600"
      become: false

    - name: Configure ssh client.
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        block: |
          # serverswitch
          Host serversw
            KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
            PubkeyAcceptedAlgorithms +ssh-rsa
            HostKeyAlgorithms +ssh-rsa
            User admin
            HostName 172.19.30.10

          # copyswitch
          Host copysw
            KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
            PubkeyAcceptedAlgorithms +ssh-rsa
            HostKeyAlgorithms +ssh-rsa
            User admin
            HostName 172.19.30.11

          # balcony switch
          Host balcsw
            KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
            PubkeyAcceptedAlgorithms +ssh-rsa
            HostKeyAlgorithms +ssh-rsa
            User admin
            HostName 172.19.30.12

          # east switch
          Host eastsw
            KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
            PubkeyAcceptedAlgorithms +ssh-rsa
            HostKeyAlgorithms +ssh-rsa
            User admin
            HostName 172.19.30.13
        marker: "# {mark} ANSIBLE MANAGED"
        state: present
      become: false

- name: Configure all hosts.
  hosts: all
  roles:
    - common
    - artis3n.tailscale
  vars_files:
    - vars/vault.yml
  tags:
    - all


- name: Configure docker hosts.
  hosts: docker
  roles:
    - geerlingguy.docker
  vars_files:
    - vars/vault.yml
  tags:
    - docker
  become: true


- name: Configure Jellyfin server.
  hosts: jellyfin
  vars_files:
    - vars/vault.yml
  tags: shared
  tasks:
    - name: Create jellyfin group.
      ansible.builtin.group:
        name: jellyfin
        state: present
      become: true

    - name: Configure adevries user.
      ansible.builtin.user:
        name: adevries
        state: present
        groups: jellyfin
        append: true
        shell: /bin/bash
      become: true

    - name: Create dingus user.
      ansible.builtin.user:
        name: dingus
        state: present
        groups:
          - dingus
          - jellyfin
        append: true
        shell: /bin/bash
      become: true

    - name: Add authorized keys to dingus user.
      ansible.posix.authorized_key:
        user: dingus
        key: "{{ dingus_key }}"
      become: true

    - name: Configure jellyfin directories
      ansible.builtin.file:
        path: /mnt/jellyfin/media
        state: directory
        mode: "0775"
        owner: root
        group: jellyfin
        recurse: true
      become: true
