---
- name: Restart_nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  become: true
- name: Start_nginx
  ansible.builtin.service:
    name: nginx
    state: started
  become: true
